name: Update NPM packages

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch:

jobs:
 update-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '8'

      - name: Install dependencies
        run: pnpm install

      - name: Check for outdated packages
        id: outdated
        run: |
          echo "::set-output name=packages::$(pnpm outdated -r --json)"

      - name: Update packages and create PRs
        run: |
          packages=$(echo "${{ steps.outdated.outputs.packages }}" | jq -r '.[] | @base64')
          for pkg in $packages; do
            _jq() {
              echo ${pkg} | base64 --decode | jq -r ${1}
            }
            pkg_name=$(_jq '.package')
            pkg_latest=$(_jq '.latest')
            pnpm add ${pkg_name}@${pkg_latest}
            git add .
            git commit -m "Update ${pkg_name} to ${pkg_latest}"
            git push origin HEAD:update-${pkg_name}
            echo "::set-output name=pr_branch::update-${pkg_name}"
          done

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          commit-message: Update npm packages
          title: Update npm packages
          body: Update npm packages to their latest versions
          labels: dependencies
          branch: ${{ steps.update-packages.outputs.pr_branch }}
