name: Update NPM packages

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch:

jobs:
 update-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '8'

      - name: Install dependencies
        run: pnpm install

      - name: Check for outdated packages
        run: pnpm outdated

      - name: Update packages and version ranges
        run: pnpm update --latest

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          commit-message: Update npm packages
          title: Update npm packages
          body: Update npm packages to their latest versions
          labels: dependencies
