name: Update Dependencies

on:
  schedule:
    # Runs every week on Monday at 00:00 UTC
    - cron: '0 0 * * MON'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: '8.15.4'

    - name: Install npm-check-updates
      run: pnpm add -g npm-check-updates

    - name: Update dependencies
      run: pnpx npm-check-updates -u

    - name: Commit and push
      run: |
        git config --global user.email "spences10apps@gmail.com"
        git config --global user.name "spences10"
        git add package.json pnpm-lock.yaml
        git diff-index --quiet HEAD || git commit -m "Update dependencies"
        git push https://${{ secrets.ACTIONS_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}

