name: Update Dependencies

on:
  schedule:
    # Runs every week on Monday at 00:00 UTC
    - cron: '0 0 * * MON'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: '8.15.4'

    - name: Install pnpm-check-updates
      run: pnpm add -g pnpm-check-updates

    - name: Update dependencies
      run: pnpx pnpm-check-updates -u

    - name: Commit and push
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add pnpm-lock.yaml
        git diff-index --quiet HEAD || git commit -m "Update dependencies"
        git push
