name: Update outdated packages

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight
  workflow_dispatch: # Allow manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '8.15.4'

      - name: Install dependencies
        run: pnpm install

      - name: Install npm-check-updates
        run: pnpm add -D npm-check-updates

      - name: Run npm-check-updates and create pull requests
        id: ncu
        run: |
          npx npm-check-updates -u --packageFile package.json
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add package.json
          git diff-index --quiet HEAD || git commit -m "Update outdated packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: ${{ github.ref }}
          delete-branch: true
          title: 'Update outdated packages'
          body: 'This pull request updates outdated packages.'
          labels: 'dependencies,automated'
          reviewers: 'your-github-username'
